- name: ADD STATIC ROUTE AND VALIDATE CHANGE
  hosts: csr1kv-1
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Add Static Route
      ios_config:
        commands:
          - ip route 8.8.4.4 255.255.255.255 10.10.0.2

    - name: Confirm Route in Routing Table
      ios_command:
        commands:
          - show ip route Static
      
      register: static_routes

    - name: Print Static Routes
      debug:
        var: static_routes