- name: ADD STATIC ROUTE AND VALIDATE CHANGE
  hosts: csr1kv-1
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Add Static Route
      ios_config:
        commands:
          - ip route 8.8.4.4 255.255.255.255 10.10.0.2

    - name: Confirm Route in Routing Table
      ios_command:
        commands:
          - show ip route static | include 8.8.4.4
      
      register: static_routes

    - name: Print Static Routes
      debug:
        var: static_routes.stdout_lines[0][0]

    - name: Confirm Static Route Exists
      assert:
        that: static_routes.stdout_lines[0][0] == "S        8.8.4.4 [1/0] via 10.10.0.2"