- name: ADD STATIC ROUTE AND VALIDATE CHANGE
  hosts: csr1kv-1
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Gather Interface facts
      ios_facts:
        gather_subset: "interfaces"
      
      register: "config"
    
    - name: Output Config
      debug: msg ="{{ config.stdout }}"