---

- name: AUDIT CSR ROUTES
  hosts: csr1kv
  connection: network_cli
  gather_facts: no

  tasks: 
    - name: Get CSR1Kv Route Table
      ios_command:
        commands: show ip route eigrp | include {{ lan_r2r_interface }}
      register: eigrp_routes

    - name: Check Route Exists
      assert:
        that: 
          - eigrp_routes.stdout[0] != ""
        success_msg: "EIGRP Route Exists"
        fail_msg: "EIGRP Route Does NOT Exist!"
      
          