---

- name: AUDIT CSR ROUTES
  hosts: csr1kv
  connection: network_cli
  gather_facts: no

  tasks: 
    - name: Get CSR1Kv Route Table
      ios_command:
        commands: show ip route eigrp | include {{ lan_r2r_interface }}
      register: eigrp_routes

    - name: Print Route Table
      debug:
        var: eigrp_routes
          