- name: CONFIRM LAN2 INTERFACE
  hosts: csr1kv-1
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Get Interfaces
      ios_facts:
        gather_subset: "interfaces"
      
      register:
        interfaces

    - name: Confirm Interface 2
      assert:
        that:
          interfaces.ansible_net_interfaces.GigabitEthernet2.ipv4[0].address == "10.10.0.1"