---

- name: PLAY 1 - Set Management Interface IP
  hosts: csr1kv
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Generate Jinja Template For Mgmt Interface
      template:
        src: ../templates/node_mgmt_interface.j2
        dest: configs/{{ inventory_hostname }}.cfg


    - name: Push Mgmt Interface Configuration
      ios_config:
        src: ../templates/node_mgmt_interface.j2
        save_when: modified

- name: PLAY 2 - Get Management Interface IP
  hosts: csr1kv
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Get facts
      ios_facts:
        gather_subset:
          - interfaces      

    - name: Output management IP
      debug:
        var: ansible_net_interfaces['{{ mgmt_interface }}']['ipv4'][0]['address']
    