---

- name: PLAY 1 - Get Management Interface IP
  hosts: csr1kv
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Something
      ios_facts:
      gather_subset: "interfaces"

    - name: Output facts
      debug:
        var: ios_facts
    