---

- name: PLAY 1 - Get Management Interface IP
  hosts: csr1kv
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Get facts
      ios_facts:
        gather_subset:
          - interfaces

      register: interfaces
      

    - name: Output management IP
      debug:
        var: interfaces
    