---

- name: CONFIGURE LAN INTERFACES
  hosts: csr1kv
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Generate template for R2R Interface
      template:
        src: ../templates/lan_r2r_interface.j2
        dest: configs/{{ inventory_hostname }}-lan_r2r_interface.cfg

    - name: Generate template for LAN Interface
      template:
        src: ../templates/lan_interface.j2
        dest: configs/{{ inventory_hostname }}-lan_interface.cfg



    - name: Configure R2R Interface
      ios_config:
        src: ../templates/lan_r2r_interface.j2
        save_when: modified

    - name: Configure LAN Interface
      ios_config:
        src: ../templates/lan_interface.j2
        save_when: modified


- name: ENABLE CDP
  hosts: csr1kv
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Enable CDP
      ios_config:
        commands: "cdp run"


- name: ENABLE ROUTING PROTOCOLS
  hosts: csr1kv
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Enable EIGRP
      ios_config:
        lines:
          - network 10.0.0.0 0.255.255.255
        parents: router eigrp 10
          

