---

- name: SETUP GUESTSHELL INTERFACE
  hosts: csr1kv-1
  connection: network_cli
  gather_facts: no

  tasks:
    - name: ENABLE NETCONF
      ios_config:
        lines:
          - netconf-yang
          

    - name: CREATE USER
      ios_config:
        lines:
          - username cisco privilege 15 password 0 cisco


    - name: ENABLE AAA
      ios_config:
        lines:
          - aaa new-model
          - aaa authorization exec default local
