---

- name: SETUP GUESTSHELL INTERFACE
  hosts: csr1kv-1
  connection: network_cli
  gather_facts: no

  tasks:
    - name: CONFIGURE VIRTUAL INTERFACE
      ios_config:
        lines:
          - ip address 192.168.35.1 255.255.255.0
          - ip nat inside
          - no mop enable
          - no mop sysid
        parents: interface VirtualPortGroup 0
          

    - name: EDIT WAN INTERFACE
      ios_config:
        lines:
          - ip nat outside
        parents: interface {{ mgmt_interface }}


    - name: CREATE ACLs
      ios_config:
        lines:
          - ip nat outside source list NAT_ACL interface {{ mgmt_interface }} overload
    
    - name: APPLY ACL
      ios_config:
        lines:
          - permit 192.168.0.0 0.0.255.255
        parents: ip access-list standard NAT_ACL

