---

- name: ENABLE AND SETUP NETCONF
  hosts: csr1kv
  connection: network_cli
  gather_facts: no

  tasks:
    - name: ENABLE NETCONF
      ios_config:
        lines:
          - netconf-yang
  

    - name: CREATE USER
      ios_config:
        commands:
          - username {{ netconf_user }} privilege 15 password 0 {{ netconf_pass }}


    - name: ENABLE AAA
      ios_config:
        lines:
          - aaa new-model
          - aaa authorization exec default local
