---

- name: CONFIGURE LAN INTERFACES
  hosts: csr1kv
  connection: network_cli
  gather_facts: no

  tasks:
    # Generate configuration for the devices and save this in the /config/ directory
    - name: Generate template for R2R Interface
      template:
        src: ../templates/lan_r2r_interface.j2
        dest: configs/{{ inventory_hostname }}-lan_r2r_interface.cfg

    - name: Generate template for LAN Interface
      template:
        src: ../templates/lan_interface.j2
        dest: configs/{{ inventory_hostname }}-lan_interface.cfg


    # Apply the template configuration to the devices
    - name: Configure R2R Interface
      ios_config:
        src: ../templates/lan_r2r_interface.j2
        save_when: modified

    - name: Configure LAN Interface
      ios_config:
        src: ../templates/lan_interface.j2
        save_when: modified

          

